name: fresh_academy_pro
description: Full clean template for Fresh Academy (RBAC, routing, Dio, Hive, charts, attendance stubs).
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: 10.2.0
  dio: ^5.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fl_chart: ^0.66.2
  table_calendar: ^3.1.2
  pdf: ^3.10.8
  printing: ^5.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
